### PR TITLE
Added Thumbs With increment 1 

### PR DESCRIPTION
**Pull request by Wake-cloud**
Hope you like it !

### CODE REVIEW

**Review by Anish570 — APPROVED** [review]
Thank you for collaborating and submitting this pull request! I really appreciate your contribution.

**Comment by Wake-cloud** [comment]
will do it again i will work on this again now ! I thank you for accepting !

**Comment by Anish570** [comment]
> will do it again i will work on this again now ! I thank you for accepting !

sure man, hey can you work of the form folder and improve it's styling and looks. Thanks.

**Comment by Wake-cloud** [comment]
off course man i am on it !

**Pull request merged**
